export const routes = [
  {
    path: '/home',
    name: 'Home',
    icon: 'pe-7s-home',
    protected: true,
  },
  {
    path: '/dashboard',
    name: 'Dashboard',
    icon: 'pe-7s-user',
    protected: true,
  },
  {
    path: '/curation-trail',
    name: 'Curation Trail',
    icon: 'pe-7s-angle-up-circle',
    protected: true,
  },
  {
    path: '/downvote-trail',
    name: 'Downvote Trail',
    icon: 'pe-7s-angle-down-circle',
    protected: true,
  },
  {
    path: '/fanbase',
    name: 'Fanbase',
    icon: 'pe-7s-like',
    protected: true,
  },
  {
    path: '/schedule-posts',
    name: 'Schedule Posts',
    icon: 'pe-7s-date',
    protected: true,
  },
  {
    path: '/upvote-comments',
    name: 'Upvote Comments',
    icon: 'pe-7s-comment',
    protected: true,
  },
  {
    path: '/claim-rewards',
    name: 'Claim Rewards',
    icon: 'pe-7s-wallet',
    protected: true,
  },
  {
    path: '/notifications',
    name: 'Notifications',
    icon: 'pe-7s-bell',
    protected: true,
  },
  {
    path: '/logout',
    name: 'Logout',
    icon: 'pe-7s-back-2',
    upgrade: true,
    protected: true,
  },
  {
    path: '/faq',
    name: 'FAQ',
    icon: 'pe-7s-home',
    upgrade: true,
    protected: false,
  },
  {
    path: '/login',
    name: 'Login',
    icon: 'pe-7s-home',
    upgrade: true,
    protected: false,
  },
];